### ISSUE TITLE
What kind of running instructions can reproduce the "noise" curve in the baseline method mentioned in the paper？

### ISSUE THREAD

**Issue by LiuXing1122** [ToruOwO/mimex#1]
Your work has been completed exceptionally well.
May I ask what kind of instructions should be executed in the mimex dmc and mimex pixmc projects to reproduce the "noise" curve in the baseline mentioned in the paper? Because I did not find the implementation instructions for the noise method in the code.
Thank you for your guidance.

**Comment by ToruOwO** [comment]
Thank you for your interest! The "noise" baseline is simply adding random action noise as in the original PPO implementation, so you can reproduce it by running without exploration (e.g. as in the [no_expl](https://github.com/ToruOwO/mimex/blob/main/mimex-pixmc/configs/expl_cfg/no_expl.yaml) config file).
